# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fadbb7cdfdf631629a995144034d2e2df6b7b7614ea9d90a59e4de3fdbf077f25ec5c8e77cde12709cef3f0c097983e41c7124a5d06bb9242191804116ebaf1

test:
  secret_key_base: 4f48eb9f7039f7e5002bd5e01952db6376cc30ef86adb0825be60931a811a646711fd3652ee3305e7dea60c2ba36685d227f0663e496b3021a77199bd9937b84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
